export const restaurants = [
  {
    id: 1,
    name: "Olive & Lemon",
    location: "Nicosia",
    cuisine: "Mediterranean",
    price: 2,
    rating: 4.7,
    dietaryTags: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    id: 2,
    name: "Sushi Corner",
    location: "Nicosia",
    cuisine: "Japanese",
    price: 3,
    rating: 4.5,
    dietaryTags: ["vegetarian", "gluten-free"],
  },
  {
    id: 3,
    name: "Taco Mesa",
    location: "Limassol",
    cuisine: "Mexican",
    price: 2,
    rating: 4.4,
    dietaryTags: ["vegetarian", "vegan"],
  },
  {
    id: 4,
    name: "Green Bowl",
    location: "Larnaca",
    cuisine: "Healthy",
    price: 1,
    rating: 4.6,
    dietaryTags: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    id: 5,
    name: "Harbor Grill",
    location: "Limassol",
    cuisine: "Mediterranean",
    price: 3,
    rating: 4.3,
    dietaryTags: ["gluten-free"],
  },
  {
    id: 6,
    name: "City Bento",
    location: "Larnaca",
    cuisine: "Japanese",
    price: 2,
    rating: 4.2,
    dietaryTags: [],
  },
];
